#购买的slot
def writeBuySlot(f,slotId,name,itemID,amount,price,specialId):
    f.write('  Slot'+str(slotId)+' = [{\n')
    f.write('    Item {\n')
    f.write('      Count = {}\n'.format(amount))
    f.write('      ItemType = "{}"\n'.format(itemID))
    f.write('      UnsafeDamage = {}\n'.format(specialId))
    f.write('      DisplayName = "&a购买：{}"\n'.format(name))
    f.write('      ItemLore = ["&a价格：${}"]\n'.format(price))
    f.write('    }\n')
    f.write('    PrimaryAction {\n')
    if specialId == 0:
        f.write('      Command = "cost: {0}; console: give %player_name% {1} {2}"\n'.format(price,itemID,amount))
    else:
        f.write('      Command = "cost: {0}; console: give %player_name% {1} {2} {3}"\n'.format(price,itemID,amount,specialId))
    f.write('      KeepInventoryOpen = true\n')
    f.write('    }\n')
    f.write('    Requirements = "%economy_balance% >= {}"\n'.format(price))
    f.write('    }, {\n')
    f.write('    Item {\n')
    f.write('      Count = {}\n'.format(amount))
    f.write('      ItemType = "{}"\n'.format(itemID))
    f.write('      UnsafeDamage = {}\n'.format(specialId))
    f.write('      DisplayName = "&a购买：{}"\n'.format(name))
    f.write('      ItemLore = [\n')
    f.write('        "&a价格：${}"\n'.format(price))
    f.write('        "&c你没有足够的金币！"\n')
    f.write('      ]\n')
    f.write('    }\n')
    f.write('  }]\n')

#出售的slot
def writeSellSlot(f,slotId,name,itemID,amount,price,specialId):
    f.write('  Slot'+str(slotId)+' = {\n')
    f.write('    Item {\n')
    f.write('      Count = {}\n'.format(amount))
    f.write('      ItemType = "{}"\n'.format(itemID))
    f.write('      UnsafeDamage = {}\n'.format(specialId))
    f.write('      DisplayName = "&c出售：{}"\n'.format(name))
    f.write('      ItemLore = ["&c价格：${}"]\n'.format(price))
    f.write('    }\n')
    f.write('    PrimaryAction {\n')
    f.write('      Command = "cost-item: {0}; cost: -{1}"\n'.format(amount,price))
    f.write('      HandheldItem {\n')
    f.write('        SearchInventory = true\n')
    f.write('        ItemType = "{}"\n'.format(itemID))
    f.write('        UnsafeDamage = {}\n'.format(specialId))
    f.write('        Count = {}\n'.format(amount))
    f.write('      }\n')
    f.write('      KeepInventoryOpen = true\n')
    f.write('    }\n')
    f.write('  }\n')