id: 4
#颜色
Color: "6"
#菜单的名称
MenuName: "羊毛"
#图标
ItemIcon: "minecraft:wool"

#是否有出售
sellMode: True

Items: [
  {
    name: "羊毛",
    itemID: "minecraft:wool",
    amount: 64,
    price: 250,
    type: "duplicate",
    endSpecialId: 15
  }
]