ItemIcon: minecraft:white_glazed_terracotta
Items:
- amount: 64
  itemID: minecraft:white_glazed_terracotta
  name: 白色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:orange_glazed_terracotta
  name: 橙色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:magenta_glazed_terracotta
  name: 品红色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:light_blue_glazed_terracotta
  name: 淡蓝色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:yellow_glazed_terracotta
  name: 黄色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:lime_glazed_terracotta
  name: 黄绿色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:pink_glazed_terracotta
  name: 粉红色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:gray_glazed_terracotta
  name: 灰色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:silver_glazed_terracotta
  name: 淡灰色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:cyan_glazed_terracotta
  name: 青色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:purple_glazed_terracotta
  name: 紫色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:blue_glazed_terracotta
  name: 蓝色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:brown_glazed_terracotta
  name: 棕色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:green_glazed_terracotta
  name: 绿色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:red_glazed_terracotta
  name: 红色带釉陶瓦
  price: 300
- amount: 64
  itemID: minecraft:black_glazed_terracotta
  name: 黑色带釉陶瓦
  price: 300
MenuName: 带釉陶瓦
id: 9
sellMode: true
