ItemIcon: minecraft:grass
Items:
- amount: 64
  itemID: minecraft:stone
  name: 石头
  price: 50
- amount: 64
  itemID: minecraft:dirt
  name: 泥土
  price: 30
- amount: 64
  itemID: minecraft:cobblestone
  name: 圆石
  price: 40
- amount: 64
  itemID: minecraft:sand
  name: 沙子
  price: 50
- amount: 64
  itemID: minecraft:sandstone
  name: 砂岩
  price: 90
- amount: 64
  itemID: minecraft:sandstone
  name: 錾制砂岩
  price: 90
  specialId: 1
- amount: 64
  itemID: minecraft:sandstone
  name: 平滑砂岩
  price: 100
  specialId: 2
- amount: 64
  itemID: minecraft:mossy_cobblestone
  name: 苔石
  price: 100
- amount: 64
  itemID: minecraft:stonebrick
  name: 石砖
  price: 40
- amount: 64
  itemID: minecraft:stonebrick
  name: 苔石砖
  price: 44
  specialId: 1
- amount: 64
  itemID: minecraft:stonebrick
  name: 裂石砖
  price: 50
  specialId: 2
- amount: 64
  itemID: minecraft:stonebrick
  name: 錾制石砖
  price: 40
  specialId: 3
- amount: 64
  itemID: minecraft:gravel
  name: 沙砾
  price: 30
- amount: 64
  itemID: minecraft:netherrack
  name: 地狱岩
  price: 50
- amount: 64
  itemID: minecraft:soul_sand
  name: 灵魂沙
  price: 60
- amount: 64
  itemID: minecraft:nether_brick
  name: 地狱砖块
  price: 74
- amount: 64
  itemID: minecraft:end_stone
  name: 末地石
  price: 64
- amount: 1
  itemID: minecraft:slime
  name: 粘黏块
  price: 150
MenuName: 建筑材料
id: 1
sellMode: true
