id: 10
#菜单的名称
MenuName: "食物"
#图标
ItemIcon: "minecraft:cake"
#是否有出售
sellMode: True

Items: [
  {
    name: "生猪排",
    itemID: "minecraft:porkchop",
    amount: 64,
    price: 320,
  },{
    name: "生牛排",
    itemID: "minecraft:beef",
    amount: 64,
    price: 320,
  },{
    name: "生鸡肉",
    itemID: "minecraft:chicken",
    amount: 64,
    price: 240,
  },{
    name: "生兔肉",
    itemID: "minecraft:rabbit",
    amount: 64,
    price: 200,
  },{
    name: "生羊肉",
    itemID: "minecraft:mutton",
    amount: 64,
    price: 250,
  },{
    name: "生鱼",
    itemID: "minecraft:fish",
    amount: 64,
    price: 100,
  },{
    name: "生鲑鱼",
    itemID: "minecraft:fish",
    amount: 64,
    price: 100,
    specialId: 1,
  },{
    name: "小丑鱼",
    itemID: "minecraft:fish",
    amount: 64,
    price: 50,
    specialId: 2,
  },{
    name: "河豚",
    itemID: "minecraft:fish",
    amount: 64,
    price: 74,
    specialId: 3,
  },{
    name: "西瓜",
    itemID: "minecraft:melon",
    amount: 64,
    price: 100,
  },{
    name: "马铃薯",
    itemID: "minecraft:potato",
    amount: 64,
    price: 40,
  },{
    name: "胡萝卜",
    itemID: "minecraft:carrot",
    amount: 64,
    price: 120,
  },{
    name: "苹果",
    itemID: "minecraft:apple",
    amount: 64,
    price: 160,
  },{
    name: "面包",
    itemID: "minecraft:bread",
    amount: 64,
    price: 200,
  },{
    name: "腐肉",
    itemID: "minecraft:rotten_flesh",
    amount: 64,
    price: 100,
  },{
    name: "蜘蛛眼",
    itemID: "minecraft:spider_eye",
    amount: 64,
    price: 70,
  },{
    name: "曲奇",
    itemID: "minecraft:cookie",
    amount: 64,
    price: 84,
  },{
    name: "附魔金苹果",
    itemID: "minecraft:golden_apple",
    amount: 1,
    price: 54000,
    specialId: 1,
  }
]