id: 8
#颜色
Color: "a"
#菜单的名称
MenuName: "陶瓦"
#图标
ItemIcon: "minecraft:stained_hardened_clay"

#是否有出售
sellMode: True

Items: [
  {
    name: "陶瓦",
    itemID: "minecraft:stained_hardened_clay",
    amount: 64,
    price: 250,
    type: "duplicate",
    endSpecialId: 15
  }
  <minecraft:white_glazed_terracotta>
<minecraft:orange_glazed_terracotta>
<minecraft:magenta_glazed_terracotta>
<minecraft:light_blue_glazed_terracotta>
<minecraft:yellow_glazed_terracotta>
<minecraft:lime_glazed_terracotta>
<minecraft:pink_glazed_terracotta>
<minecraft:gray_glazed_terracotta>
<minecraft:silver_glazed_terracotta>
<minecraft:cyan_glazed_terracotta>
<minecraft:purple_glazed_terracotta>
<minecraft:blue_glazed_terracotta>
<minecraft:brown_glazed_terracotta>
<minecraft:green_glazed_terracotta>
<minecraft:red_glazed_terracotta>
<minecraft:black_glazed_terracotta>
]