ItemIcon: minecraft:glass
Items:
- amount: 64
  itemID: minecraft:glass
  name: 玻璃
  price: 150
- amount: 64
  endSpecialId: 15
  itemID: minecraft:stained_glass
  name: 玻璃[彩色]
  price: 160
  type: duplicate
- amount: 64
  itemID: botania:managlass
  name: 魔力玻璃
  price: 200
MenuName: 玻璃
id: 2
sellMode: true
