ItemIcon: minecraft:emerald
Items:
- amount: 64
  itemID: minecraft:coal
  name: 煤炭
  price: 130
- amount: 64
  itemID: minecraft:coal
  name: 木炭
  price: 130
  specialId: 1
- amount: 1
  itemID: minecraft:iron_ingot
  name: 铁锭
  price: 100
- amount: 1
  itemID: minecraft:gold_ingot
  name: 金锭
  price: 750
- amount: 1
  itemID: minecraft:diamond
  name: 钻石
  price: 1000
- amount: 1
  itemID: minecraft:emerald
  name: 绿宝石
  price: 800
- amount: 64
  itemID: minecraft:glowstone_dust
  name: 萤石粉
  price: 640
- amount: 64
  itemID: minecraft:redstone
  name: 红石
  price: 320
- amount: 64
  itemID: minecraft:dye
  name: 青金石
  price: 320
  specialId: 4
- amount: 1
  itemID: minecraft:quartz_block
  name: 石英块
  price: 50
- amount: 1
  itemID: minecraft:coal_block
  name: 煤炭块
  price: 22.5
- amount: 1
  itemID: minecraft:iron_block
  name: 铁块
  price: 900
- amount: 1
  itemID: minecraft:gold_block
  name: 金块
  price: 6750
- amount: 1
  itemID: minecraft:diamond_block
  name: 钻石块
  price: 9000
- amount: 1
  itemID: minecraft:emerald_block
  name: 绿宝石块
  price: 9000
- amount: 64
  itemID: minecraft:glowstone
  name: 萤石
  price: 2560
- amount: 64
  itemID: minecraft:redstone_block
  name: 红石块
  price: 2880
- amount: 64
  itemID: minecraft:lapis_block
  name: 青金石块
  price: 2880
MenuName: 矿物
id: 0
sellMode: true
