ItemIcon: minecraft:cake
Items:
- amount: 64
  itemID: minecraft:porkchop
  name: 生猪排
  price: 320
- amount: 64
  itemID: minecraft:beef
  name: 生牛排
  price: 320
- amount: 64
  itemID: minecraft:chicken
  name: 生鸡肉
  price: 240
- amount: 64
  itemID: minecraft:rabbit
  name: 生兔肉
  price: 200
- amount: 64
  itemID: minecraft:mutton
  name: 生羊肉
  price: 250
- amount: 64
  itemID: minecraft:fish
  name: 生鱼
  price: 100
- amount: 64
  itemID: minecraft:fish
  name: 生鲑鱼
  price: 100
  specialId: 1
- amount: 64
  itemID: minecraft:fish
  name: 小丑鱼
  price: 50
  specialId: 2
- amount: 64
  itemID: minecraft:fish
  name: 河豚
  price: 74
  specialId: 3
- amount: 64
  itemID: minecraft:melon
  name: 西瓜
  price: 100
- amount: 64
  itemID: minecraft:potato
  name: 马铃薯
  price: 40
- amount: 64
  itemID: minecraft:carrot
  name: 胡萝卜
  price: 120
- amount: 64
  itemID: minecraft:apple
  name: 苹果
  price: 160
- amount: 64
  itemID: minecraft:bread
  name: 面包
  price: 200
- amount: 64
  itemID: minecraft:rotten_flesh
  name: 腐肉
  price: 100
- amount: 64
  itemID: minecraft:spider_eye
  name: 蜘蛛眼
  price: 70
- amount: 64
  itemID: minecraft:cookie
  name: 曲奇
  price: 84
- amount: 1
  itemID: minecraft:golden_apple
  name: 附魔金苹果
  price: 54000
  specialId: 1
MenuName: 食物
id: 10
sellMode: true
