ItemIcon: minecraft:glass_pane
Items:
- amount: 64
  itemID: minecraft:glass_pane
  name: 玻璃板
  price: 56.25
- amount: 64
  endSpecialId: 15
  itemID: minecraft:stained_glass_pane
  name: 玻璃板[彩色]
  price: 60
  type: duplicate
- amount: 64
  itemID: botania:managlasspane
  name: 魔力玻璃板
  price: 75
MenuName: 玻璃版
id: 3
sellMode: true
