id: 5
#颜色
Color: "9"
#菜单的名称
MenuName: "羊毛地毯"
#图标
ItemIcon: "minecraft:carpet"

#是否有出售
sellMode: True

Items: [
  {
    name: "羊毛地毯",
    itemID: "minecraft:carpet",
    amount: 64,
    price: 250,
    type: "duplicate",
    endSpecialId: 15
  }
]